import os
Import('env')

# Stuff for pulling in TPLs
cwd = Dir('.')

objs = []

objs.append(env.Object('files.cpp'))
objs.append(env.Object('filescrubber.cpp'))
objs.append(env.Object('inputproc.cpp'))
objs.append(env.Object('pinmesh_cyl.cpp'))
objs.append(env.Object('pinmesh_rect.cpp'))
objs.append(env.Object('pinmesh.cpp'))
objs.append(env.Object('materiallib.cpp'))

Import('lib_objs')

objs = objs + lib_objs


mocc = env.Program(target="mocc", source=["mocc.cpp"] + objs)


Default(mocc)